//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class htmlGeneratorResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal htmlGeneratorResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsFormsApp1.Resources.htmlGeneratorResource", typeof(htmlGeneratorResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wkp-date.
        /// </summary>
        internal static string attrDateField {
            get {
                return ResourceManager.GetString("attrDateField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to k-options=&quot;{0}&quot;.
        /// </summary>
        internal static string attrKOptionsForDropdown {
            get {
                return ResourceManager.GetString("attrKOptionsForDropdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ctrl.populateDropDownList(null, @Html.Raw(ViewData[&quot;{0}&quot;]).ToString().Replace(&quot;\&quot;&quot;, &quot;\&apos;&quot;)).
        /// </summary>
        internal static string attrKOptionValueForDropdownViewData {
            get {
                return ResourceManager.GetString("attrKOptionValueForDropdownViewData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to multiple=&quot;true&quot;.
        /// </summary>
        internal static string attrLookupMultiple {
            get {
                return ResourceManager.GetString("attrLookupMultiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maxlength=&quot;{0}&quot;.
        /// </summary>
        internal static string attrMaxLength {
            get {
                return ResourceManager.GetString("attrMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wkp-mes-ano.
        /// </summary>
        internal static string attrMonthField {
            get {
                return ResourceManager.GetString("attrMonthField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to k-min=&quot;{0}&quot;.
        /// </summary>
        internal static string attrNumberMax {
            get {
                return ResourceManager.GetString("attrNumberMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to k-max=&quot;{0}&quot;.
        /// </summary>
        internal static string attrNumberMin {
            get {
                return ResourceManager.GetString("attrNumberMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to k-step=&quot;{0}&quot;.
        /// </summary>
        internal static string attrNumberStep {
            get {
                return ResourceManager.GetString("attrNumberStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ng-required=&quot;true&quot;.
        /// </summary>
        internal static string attrRequired {
            get {
                return ResourceManager.GetString("attrRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to k-data-value-field=&quot;&apos;Value&apos;&quot;
        ///k-data-text-field=&quot;&apos;Text&apos;&quot;.
        /// </summary>
        internal static string attrTextValueForDropdown {
            get {
                return ResourceManager.GetString("attrTextValueForDropdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;input id={{{{ctrl.form.fields.{0}.fieldName}}}}
        ///                            name={{{{ctrl.form.fields.{0}.fieldName}}}}
        ///                            kendo-date-picker
        ///                            {1}
        ///                            ng-model=&quot;ctrl.{2}.{0}&quot;
        ///                            ng-model-options=&quot;{{ updateOn: &apos;default&apos; }}&quot;
        ///                            ng-disabled=&quot;ctrl.pageMode.detail&quot;
        ///                            ng-change=&quot;&quot;
        ///                            k-min=&quot;&quot;
        ///                            k-max=&quot;&quot;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string fieldDateMonth {
            get {
                return ResourceManager.GetString("fieldDateMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;input kendo-drop-down-list 
        ///                   id={{{{ctrl.form.fields.{0}.fieldName}}}}
        ///                   name={{{{ctrl.form.fields.{0}.fieldName}}}}
        ///                   {1}      
        ///                   ng-disabled=&quot;ctrl.pageMode.detail&quot;
        ///                   class=&quot;k-textbox&quot;
        ///                   {2}
        ///                   ng-model=&quot;ctrl.{3}.{0}&quot;
        ///                   /&gt;.
        /// </summary>
        internal static string fieldDropdown {
            get {
                return ResourceManager.GetString("fieldDropdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;wkp-generic-lookup id={{{{ctrl.form.fields.{0}.fieldName}}}}
        ///                            name={{{{ctrl.form.fields.{0}.fieldName}}}}
        ///                            placeholder=&quot;@SharedResource.Selecione&quot;
        ///                            title=&quot;{4}&quot;
        ///                            {1}
        ///                            options=&quot;ctrl.{2}&quot;
        ///                            accessors=&quot;ctrl.{2}.accessors&quot;
        ///                            is-disabled=&quot;ctrl.pageMode.detail&quot;
        ///                            selected-data=&quot;ctrl.{3}.{0}&quot;&gt;
        ///&lt;/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string fieldLookup {
            get {
                return ResourceManager.GetString("fieldLookup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;input id={{{{ctrl.form.fields.{0}.fieldName}}}}
        ///                   name={{{{ctrl.form.fields.{0}.fieldName}}
        ///}}                   ng-disabled=&quot;ctrl.pageMode.detail&quot;
        ///                   type=&quot;number&quot;
        ///                   ng-model=&quot;ctrl.{1}.{0}&quot;
        ///                   k-ng-model=&quot;ctrl.{1}.{0}&quot;
        ///                   kendo-numeric-text-box
        ///                   k-format=&quot;&apos;n0&apos;&quot;
        ///                   {2} {3} {4} ng-model-options=&quot;{{updateOn: &apos;blur&apos;}}&quot; 
        ///                   k-on-change=&quot;&quot; /&gt;.
        /// </summary>
        internal static string fieldNumber {
            get {
                return ResourceManager.GetString("fieldNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;textarea id={{{{ctrl.form.fields.{0}.fieldName}}}}
        ///                  name={{{{ctrl.form.fields.{0}.fieldName}}}}
        ///                  class=&quot;k-textbox&quot;
        ///                  ng-disabled=&quot;ctrl.pageMode.detail&quot;
        ///                  rows=&quot;3&quot;
        ///                  {1}
        ///                  ng-model=&quot;ctrl.{2}.{0}&quot;
        ///                  style=&quot;width:100%;resize:none;&quot;
        ///                  ng-required=&quot;true&quot;&gt;
        ///&lt;/textarea&gt;.
        /// </summary>
        internal static string fieldTextArea {
            get {
                return ResourceManager.GetString("fieldTextArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;input id={{{{ctrl.form.fields.{0}.fieldName}}}}
        /// name={{{{ctrl.form.fields.{0}.fieldName}}}}
        ///               ng-disabled=&quot;ctrl.pageMode.detail&quot;
        ///               type=&quot;text&quot;
        ///               {1}
        ///               ng-model=&quot;ctrl.{2}.{0}&quot;
        ///               class=&quot;k-textbox&quot; /&gt;.
        /// </summary>
        internal static string fieldTextBox {
            get {
                return ResourceManager.GetString("fieldTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;input id={{{{ctrl.form.fields.{0}.fieldName}}
        ///}}
        ///	name={{{{ctrl.form.fields.{0}.fieldName}}}}
        ///
        ///	ng-disabled=&quot;ctrl.pageMode.detail&quot;
        ///
        ///	type=&quot;text&quot;
        ///
        ///	maxlength=&quot;8&quot;
        ///
        ///	wkp-time-picker-mask
        ///                   
        ///	kendo-time-picker
        ///                   
        ///	ng-model=&quot;ctrl.{1}.{0}&quot;
        ///                   
        ///	{2}                 
        ///	class=&quot;k-textbox&quot; /&gt;.
        /// </summary>
        internal static string fieldTime {
            get {
                return ResourceManager.GetString("fieldTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;row-section-title&quot;&gt;
        ///        &lt;span class=&quot;section&quot;&gt;{0}&lt;/span&gt;
        ///    &lt;/div&gt;.
        /// </summary>
        internal static string fieldTitle {
            get {
                return ResourceManager.GetString("fieldTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (function () {{
        ///    angular.module(&apos;&apos;)
        ///        .factory(&apos;classes.{0}&apos;, {0});
        ///
        ///    function {0}() {{
        ///        var {0}= function (parent) {{
        ///            this[parent.name] = parent.name;
        ///            {1}
        ///        }}
        ///
        ///        return {0};
        ///    }}
        ///}})();.
        /// </summary>
        internal static string fileJsClassStructure {
            get {
                return ResourceManager.GetString("fileJsClassStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @{
        ///    string msgs = ViewData[&quot;msg&quot;] == null ? &quot;&quot; : (string)ViewData[&quot;msg&quot;];
        ///    string Ids = ViewData[&quot;ids&quot;] == null ? &quot;&quot; : string.Join(&quot;,&quot;, (int[])ViewData[&quot;ids&quot;]);
        ///
        ///    var initObject = new
        ///    {
        ///        resources = new
        ///        {
        ///            msg = msgs,
        ///        },
        ///        rotinaId = ViewBag.RotinaId
        ///    };
        ///}.
        /// </summary>
        internal static string initialResourceCode {
            get {
                return ResourceManager.GetString("initialResourceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/div&gt;.
        /// </summary>
        internal static string tagDivClose {
            get {
                return ResourceManager.GetString("tagDivClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div ng-cloak id=&quot;{0}&quot; ng-controller=&quot;{1} as ctrl&quot;
        ///     ng-init=&quot;ctrl.pageInit(@JsonConvert.SerializeObject(initObject))&quot; ng-hidden=&quot;isLoading&quot;&gt;.
        /// </summary>
        internal static string tagDivControllerStart {
            get {
                return ResourceManager.GetString("tagDivControllerStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!-- Mensagens de Erro --&gt;
        ///    &lt;div class=&quot;row&quot;&gt;
        ///        @Html.NgErrorSummary(@SharedResource.msgTituloAlertInconsistencia, &quot;ctrl&quot;)
        ///        &lt;alert ng-repeat=&quot;alert in ctrl.alerts&quot; type=&quot;{{alert.type}}&quot; close=&quot;ctrl.closeAlert($index)&quot;&gt;&lt;h4&gt;@SharedResource.msgTituloAlertSucesso&lt;/h4&gt;{{alert.msg}}&lt;/alert&gt;
        ///    &lt;/div&gt;.
        /// </summary>
        internal static string tagDivErrors {
            get {
                return ResourceManager.GetString("tagDivErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;col-xs-12 {0}&quot;&gt;.
        /// </summary>
        internal static string tagDivStart {
            get {
                return ResourceManager.GetString("tagDivStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;row&quot;&gt;
        ///        &lt;wkp-generic-crud-nav-bar action-change-item=&quot;ctrl.navbar.changeItem(arg)&quot;
        ///                                  action-save-entity-and-next=&quot;ctrl.navbar.saveEntityAndNext()&quot;
        ///                                  action-save-entity=&quot;ctrl.navbar.saveEntity()&quot;
        ///                                  action-save-entity-and-new=&quot;ctrl.navbar.saveEntityAndNew()&quot;
        ///                                  action-edit-entity=&quot;ctrl.navbar.editEntity()&quot;
        ///                                  action-delete-entity= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string tagDivToolBar {
            get {
                return ResourceManager.GetString("tagDivToolBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/form&gt;.
        /// </summary>
        internal static string tagFormClose {
            get {
                return ResourceManager.GetString("tagFormClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;form ng-submit=&quot;&quot; novalidate name=&quot;ctrl.{{ctrl.form.name}}&quot; ng-init=&quot;ctrl.pageLoad(&apos;@ViewData[&quot;{0}&quot;]&apos;, &apos;@ViewData[&quot;isDetail&quot;].ToString()&apos;, &apos;@Ids&apos;)&quot;&gt;.
        /// </summary>
        internal static string tagFormStart {
            get {
                return ResourceManager.GetString("tagFormStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;label&gt;{0}&lt;/label&gt;.
        /// </summary>
        internal static string tagLabel {
            get {
                return ResourceManager.GetString("tagLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;popError&quot; ng-show=&quot;ctrl.{{{{{0}}}}}.{{{{ctrl.form.fields.{1}.fieldName}}}}.$invalid &amp;&amp; ctrl.{{{{{0}}}}}.{{{{ctrl.form.fields.{1}.fieldName}}}}.$dirty&quot;&gt;
        ///            &lt;span ng-show=&quot;ctrl.{{{{{0}}}}}.{{{{ctrl.form.fields.{1}.fieldName}}}}.$error.required&quot; class=&quot;fieldError&quot;&gt;
        ///                
        ///            &lt;/span&gt;
        ///&lt;/div&gt;.
        /// </summary>
        internal static string tagRequiredField {
            get {
                return ResourceManager.GetString("tagRequiredField", resourceCulture);
            }
        }
    }
}
